### ISSUE TITLE
Allow building the project against various USD build configurations

### ISSUE THREAD

**Issue by sirpalee** [sideeffects/HoudiniUsdBridge#1]
USD's build system allows easy prefixing of library names, this should be supported by FindUSD.cmake.

This can be done by modifying the FindUSD.cmake and using a cmake variable that holds all the libraries.

**Comment by sirpalee** [comment]
I started working on a PR for this: https://github.com/sirpalee/HoudiniUsdBridge/commit/1df0005bd5f5ddb7cbd2ed96d2b72c77d60986d8

**Comment by marktucker** [comment]
I believe this issue is the same as the one here: https://github.com/sideeffects/HoudiniUsdBridge/issues/4
Which includes a PR, which I hope to be accepting soon.

**Comment by marktucker** [comment]
Sorry, https://github.com/sideeffects/HoudiniUsdBridge/pull/6 was the original issue with the PR, though #4 has since subsumed this.
