### ISSUE TITLE
USD status messages displayed as warnings

### ISSUE THREAD

**Issue by glm-dtrusca** [sideeffects/HoudiniUsdBridge#10]
Hello,

We wrote a plugin that creates geometry procedurally using dynamic payloads. It is very much based on the usdDancingCubesExample sample. We're displaying several status messages when loading the custom usd file format. It seems that all messages are showed as warnings in Houdini on the File LOP, even though they are created through the TF_STATUS macro.

When looking at the file src\houdini\lib\H_USD\HUSD\HUSD_ErrorScope.C, `HUSD_ErrorDelegate::IssueStatus` calls `myMgr->addWarning`, which explains why all USD status messages are dispalyed as warnings.

Is this intentional or just a bug ?

Houdini version: 18.0.287
USD versiion: 19.11

**Comment by marktucker** [comment]
Thanks for pointing this out. This should be fixed in 18.0.374.
