### ISSUE TITLE
Custom ArResolver not being loaded in 18.0.372

### ISSUE THREAD

**Issue by nrusch** [sideeffects/HoudiniUsdBridge#11]
Today I tried building the 18.0.370 cut of this repo against 18.0.372 and testing it in our environment, and it seems that the most recent set of changes have broken loading of at least some custom USD plugins. It's unclear whether this only affects custom `ArResolver` plugins, but so far that's the only thing I've had an issue with.

Commenting out [this block](https://github.com/sideeffects/HoudiniUsdBridge/commit/9745a802f88e443c8a17b0b69d24791d17afd75f#diff-d832e18528f79cb383345c6ebb8c63d6R84-R97) causes the resolver to load and work as expected. I'm not sure I quite understand why that code is necessary, since at first glance it looks like the kind of thing that `PXR_PLUGINPATH_PATH` (or its site-specific equivalent) would handle when USD initializes.

It's also not clear to me why that code would be causing issues, but I haven't done a ton of investigation. However, using the brute-force `LD_DEBUG=libs` method, I have at least confirmed that the plugin library for our resolver isn't even initialized when that block of code is in place.

**Comment by marktucker** [comment]
That's odd... The code only adds additional plugin paths, so I don't see why it would be stopping a plugin from loading. Where is your ArResolver plugin located? How do you ensure it's install location is part of the USD plugin path?

The prupose if that change is so that third party renderers can easily have their render delegates show up in LOPs by simply adding an entry to the HOUDINI_PATH, rather than also having to modify the PXR_PLUGINPATH_NAME.

**Comment by nrusch** [comment]
All of our internal packages (USD, HUSD, our resolver, other schema modules, etc.) are released in separate directory trees, and none of them are in the Houdini install tree.

We use `PXR_PLUGINPATH_NAME` to find and load USD plugins, except our USD library uses a different environment variable name (`LPXR_PLUGINPATH_NAME`) for clarity. We also build USD with a custom namespace.

For HUSD, we use `HOUDINI_DSO_EXCLUDE_PATTERN` to prevent Houdini from loading various factory plugins that would pull in the shipped USD libraries via an `rpath` (e.g. `USD_Ops.so`, `USD_Plugins.so`, etc.), and then we put the path to our released versions on `HOUDINI_DSO_PATH`, mirroring the same directory structure found in `$HFS/houdini/dso`.

I'm doing some additional tests to see if I can spot a library load order difference with and without that code block enabled, and I'll follow up with anything I learn.

> The prupose if that change is so that third party renderers can easily have their render delegates show up in LOPs by simply adding an entry to the HOUDINI_PATH, rather than also having to modify the PXR_PLUGINPATH_NAME.

Hmm... I'm not sure that would really work as intended in the wild, since it assumes plugins will be installed in a `usd_plugins` subdirectory. As an example, arnold-usd does not adhere to this pattern by default, and also allows the plugins subdirectory to be configured at build time.

**Comment by nrusch** [comment]
OK, I figured it out. The cause was `USD_FS.so` having moved into a subdirectory of `$HFS/dso` between Houdini builds, so the path I had in `HOUDINI_DSO_EXCLUDE_PATTERN` was no longer preventing that lib from being loaded at Houdini startup.

As a result, the `rpath` linkage in the stock `USD_FS.so` caused the stock Houdini USD libs to get loaded instead of ours, and thus the wrong environment variable was scanned for USD plugins.

There's something up with Karma still, but I'll open a separate issue for that.

Sorry for the noise!
