### ISSUE TITLE
hdPrman dependency

### ISSUE THREAD

**Issue by fabal** [sideeffects/HoudiniUsdBridge#13]
A library link dependency has been added to `hdPrman` in a916bd3ab9b518ac58598851fb9835237fde5a54 but we're not building it.
Is it something which could be optional?

> Also just noting there's a typo [here](https://github.com/sideeffects/HoudiniUsdBridge/commit/a916bd3ab9b518ac58598851fb9835237fde5a54#diff-95e351a3805a1dafa85bf20b81d086e6R218), it should be `usdSkelImaging` instead.

**Comment by nrusch** [comment]
Yeah, we're in the same boat. I'm not actually sure hdPrman is a required link, since removing it seems to mostly work (I'm getting occasional crashes, but I don't currently suspect they are related).

**Comment by marktucker** [comment]
Removed in both 18.0 (https://github.com/sideeffects/HoudiniUsdBridge/commit/2fc7cb1a52c7f0e821459c81643d23a2b2da222c) and 18.5 (https://github.com/sideeffects/HoudiniUsdBridge/commit/90f378d82d96af481c37085c02163ac246e9593a) branches.
