### ISSUE TITLE
Karma delegate does not work

### ISSUE THREAD

**Issue by nrusch** [sideeffects/HoudiniUsdBridge#15]
The Karma render delegate does not currently work when using a custom build of this repo. It shows up in the viewport menu, but when I pick it, the viewer just redraws with the currently active delegate, and when I look in the viewport menu again, the Karma entry has disappeared.

I did notice that there is a `$HFS/houdini/dso/usd/USD_Karma.so` is not mirrored by any of the compiled components in this repo. I'm not sure if the contents of that lib are being built into one of the other libs, but that's my prime suspect right now.

**Comment by marktucker** [comment]
This should work in the 19.0 and 19.5 branches.
