### ISSUE TITLE
fatal error: SOP_UnpackUSD-2.0.proto.h: No such file or directory

### ISSUE THREAD

**Issue by sanikache** [sideeffects/HoudiniUsdBridge#19]
Hello Mark and team,

There is a missing header file "SOP_UnpackUSD-2.0.proto.h" included here in https://github.com/sideeffects/HoudiniUsdBridge/blob/houdini19.0.383/src/houdini/custom/USDOP/SOP_LOP-2.0.C#L18

```
src/houdini/custom/USDOP/SOP_UnpackUSD-2.0.C:18:10: fatal error: SOP_UnpackUSD-2.0.proto.h: No such file or directory
   18 | #include "SOP_UnpackUSD-2.0.proto.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Cheers
Ibrahim.

**Comment by sanikache** [comment]
Ah! Thanks @sosh! We build using SCons and there is no mention of this in any of the cmake files. I will try cmake instead.

**Comment by marktucker** [comment]
Has this been resolved?

**Comment by sanikache** [comment]
Yes @marktucker! It's been resolved. 
Thanks.
