### ISSUE TITLE
Missing CMakeSources.cmake file

### ISSUE THREAD

**Issue by migo-robben** [sideeffects/HoudiniUsdBridge#2]
When I want to build the HoudiniUsdBridge Project use cmake, CMake Error occurs as follow:

CMake Error at src/houdini/custom/USDFS/CMakeLists.txt:3 (include):
  include could not find load file:
      /HoudiniUsdBridge/src/houdini/custom/USDFS/CMakeSources.cmake

How to fix it? Thank you

**Comment by marktucker** [comment]
I've submitted a change to the Houdini baseline to add this file. It should show up as a commit here tomorrow.

**Comment by marktucker** [comment]
This missing file has been added by this commit: https://github.com/sideeffects/HoudiniUsdBridge/commit/e2ded032a2358d21853ec638853acdbe6df0fc6b
