### ISSUE TITLE
Build error on the houdini19.0 branch

### ISSUE THREAD

**Issue by jossh-h** [sideeffects/HoudiniUsdBridge#20]
Hi all,

We noticed the following build error and wanted to flag it with the team:

```
/scratch/joshhe/repos/AL_HoudiniUSD/h19.0/src/houdini/lib/H_USD/HUSD/HUSD_Imaging.C:92:8: error: invalid use of template-name 'SYS_AtomicInt' without an argument list
 static SYS_AtomicInt        theTextureCacheRenders(0);
        ^~~~~~~~~~~~~
In file included from /depts/rnd/dev/joshhe/packages/PIPE-houdiniusd-19.0.616/houdiniDevKit/19.0.616/houdini/toolkit/include/UT/UT_IntrusivePtr.h:15:0,
                 from /scratch/joshhe/repos/AL_HoudiniUSD/h19.0/src/houdini/lib/H_USD/HUSD/HUSD_DataHandle.h:30,
                 from /scratch/joshhe/repos/AL_HoudiniUSD/h19.0/src/houdini/lib/H_USD/HUSD/HUSD_Imaging.h:29,
                 from /scratch/joshhe/repos/AL_HoudiniUSD/h19.0/src/houdini/lib/H_USD/HUSD/HUSD_Imaging.C:25:
/depts/rnd/dev/joshhe/packages/PIPE-houdiniusd-19.0.616/houdiniDevKit/19.0.616/houdini/toolkit/include/SYS/SYS_AtomicInt.h:19:7: note: 'template<class T> class SYS_AtomicInt' declared here
 class SYS_AtomicInt
```
We have made the  following change in [HUSD_Imaging.C](https://github.com/sideeffects/HoudiniUsdBridge/blob/houdini19.0/src/houdini/lib/H_USD/HUSD/HUSD_Imaging.C#L92) 
`static SYS_AtomicInt<int>        theTextureCacheRenders(0)`

which resolves the build error but wanted to confirm the fix.

Thanks!

fyi we are building `houdini-19.0.611` at this [commit](https://github.com/sideeffects/HoudiniUsdBridge/commit/5a8ace81cc16d5c03616c560264a927312692609)

**Comment by marktucker** [comment]
That is certainly a valid fix, and I'm happy to merge that change into our baseline so it will be published in the next update to the HoudiniUsdBridge (19.0.623).

However I'm a little concerned that this is being flagged as an error for you. None of our compilers have ever flagged this code, which makes me wonder what compiler you're using, and that makes me worry there may be incompatibilities between the code generated by your compiler and the rest of Houdini. But hopefully that's just me being paranoid.

Anyway, thanks for the contribution. I'll let you close this issue if you're happy with the end result.

**Comment by fabal** [comment]
Hey @marktucker , I think in that case the compiler's version matters less (we use devtoolset 6) than the c++ standard used. The bridge's cmake configuration uses c++14 whereas the argument deduction at play here (CTAD) was introduced in c++17. Unfortunately, we haven't switched to c++17 yet.
But if that's what I think it is (I'm getting a successful build with c++17), that would mean that you build the bridge with c++17 and not c++14.

**Comment by marktucker** [comment]
You are right that Houdini itself (including the HoudiniUsdBridge libraries) are built with C++17 (as per the VFX reference platform). However I have in the past built the HoudiniUsdBridge using just the CMake files that are in the repository and never saw this compiler issue (in spite of the fact that the CMAKE_CXX_STANDARD is set to 14 in CMakeLists.txt). I suppose it si possible this code was added since the last timeI tried building the HoudiniUsdBridge.

**Comment by jossh-h** [comment]
Great thanks all! ill close this issue
