### ISSUE TITLE
use of hboost instead of BOOST_NS in HUSD_PythonConverter.C in h19.5 branch

### ISSUE THREAD

**Issue by sosh** [sideeffects/HoudiniUsdBridge#23]
In "src/houdini/lib/H_USD/HUSD/HUSD_PythonConverter.C" (lines 213,214) please replace hboost with BOOST_NS namespace.

**Comment by marktucker** [comment]
Thanks for pointing this out! This was done in 19.5.362 (https://github.com/sideeffects/HoudiniUsdBridge/commit/73baddc3beb4c629ed052b8f459f41c5fb5d6f3e).
