### ISSUE TITLE
Missing member function replaceStrings in class GA_ATIString

### ISSUE THREAD

**Issue by msercheli** [sideeffects/HoudiniUsdBridge#26]
Getting this error while building:

src/houdini/custom/USDOP/SOP_UnpackUSD-2.0.C:325:20: error: ‘class GA_ATIString’ has no member named ‘replaceStrings’; did you mean ‘replaceString’?

I looked into the the header (from the Houdini installation directory):
    hfs19.5.368/toolkit/include/GA/GA_ATIString.h (line 241) and it offers the method replaceString but there is no replaceStrings method available.

Build environment:

- HoudiniUsdBridge version 19.5
- Houdini version 19.5.368
- USD version 22.11
- Linux CentOS-7

**Comment by marktucker** [comment]
You have to match the HoudiniUsdBridge as exactly as possible with the Houdini version you're building against. In the case of 19.5.368, that's https://github.com/sideeffects/HoudiniUsdBridge/tree/1e7a557202808486e128cfaa054ca6ef13b2e310 (the commit messages tie a given HoudiniUsdBridge revision to a given Houdini version).
