### ISSUE TITLE
USD library linkage no longer works with Houdini 18+

### ISSUE THREAD

**Issue by nrusch** [sideeffects/HoudiniUsdBridge#4]
In Houdini 18, the previous monolithic USD library (`libpxr_usd_ms.so`) was replaced with individual component libraries (`libpxr_sdf.so`, `libpxr_usd.so`, `libpxr_usdGeom.so`, etc.)

The Houdini executables that rely on USD (of which there are many) now all link directly against each of these component libraries.

However, the Solaris bridge code has not been updated to account for this: it is still building a stub "monolithic" library. Thus, it is not currently possible to deploy this project for Houdini 18 unless the library name prefix of the custom USD build being used happens to match the one used by Houdini (`libpxr_`).

I was somewhat hopeful that the various binaries in Houdini might link against USD indirectly via a single shim library or something, but this is not the case.

**Comment by nrusch** [comment]
@marktucker  Not sure you're CC'ed on all activity in this repo, so just mentioning you for visibility.

**Comment by nrusch** [comment]
I've got a solution for this in the works, so hopefully I'll have a PR shortly.

**Comment by marktucker** [comment]
I am cc'ed, I just haven't had much time to think about this yet... If you want to submit a PR that would be awesome!

**Comment by marktucker** [comment]
Finally had a chance to try this out. Thanks very much! I'll merge it into the master branch too.
