### ISSUE TITLE
Karma-related source code is not included

### ISSUE THREAD

**Issue by nrusch** [sideeffects/HoudiniUsdBridge#5]
This repo does not currently include the UsdKarma source, although it is included in the `toolkit` directory of a Houdini install.

There's also a USD plugin in `$HFS/houdini/dso/usd_plugins/hdKarma` that references the `BRAY_HdKarma.so` library, but that library is not currently being built as part of this project (though that library does link against USD). I suspect this may cause issues attempting to use the Karma render delegate, though I have not tested this yet.

**Comment by nrusch** [comment]
Just to add some more context, one of the side-effects (I assume) is that we can't use the Karma render delegate right now.

**Comment by marktucker** [comment]
Sorry, I forgot to update this issue. The karma render delegate code was added to the repository a couple of weeks ago.

**Comment by nrusch** [comment]
Oh great, thanks very much!
