### ISSUE TITLE
Install headers & plugInfo.json ?

### ISSUE THREAD

**Issue by AlexSchwank** [sideeffects/HoudiniUsdBridge#9]
Hi,

We're patching the CMakeLists.txt files to install headers and plugInfo.json alongside with the libs. I don't think everyone needs this but it would be nice to have a cmake option to install these files if required.

@marktucker  what do you think?

Alex

**Comment by marktucker** [comment]
The COPY_HOUDINI_USD_PLUGINS option causes the usd_plugins diretory from $HFS/houdini/dso to be copied to the installation directory. Is this what you're looking for? Or perhaps this has just faded to obscurity in the past two years...
